<?php echo $this->doctype(); ?>

<html lang="zh">
<head>
	<meta charset="utf-8">
        <?php echo $this->headTitle($this->translate('Happy Journey'))->setSeparator(' - ')->setAutoEscape(false)?>
        <?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0')?>
        
        <!-- Le styles -->
        <?php echo $this->headLink(array(
										'rel' => 'shortcut icon',
										'type' => 'image/vnd.microsoft.icon',
										'href' => $this->basePath () . '/images/favicon.ico' 
									))->prependStylesheet ( $this->basePath () . '/css/bootstrap.css' )
        								->prependStylesheet ( $this->basePath () . '/css/style.css' )
        								->prependStylesheet ( $this->basePath () . '/css/extra-style.css' )
        								->prependStylesheet ( $this->basePath () . '/css/flexslider.css' )
        								->prependStylesheet ( 'https://code.jquery.com/ui/1.12.0/themes/base/jquery-ui.css' )
        ?>
        <link href='//fonts.googleapis.com/css?family=Open+Sans:400,800italic,800,700italic,700,600italic,600,400italic,300italic,300' rel='stylesheet' type='text/css'>

		<!-- Scripts -->
        <?php echo $this->headScript ()->prependFile ( $this->basePath () . '/js/responsiveslides.min.js' )
        								->prependFile ( $this->basePath () . '/js/jquery.flexslider.js' )
        								->prependFile ( $this->basePath () . '/js/main.js' ) 
        								->prependFile ( $this->basePath () . '/js/bootstrap.js' )
        								->prependFile ( 'https://code.jquery.com/ui/1.12.0/jquery-ui.js' )
        								->prependFile ( $this->basePath () . '/js/jquery-1.11.1.min.js' )
        ?>
</head>
<body>
	<div class="header">
		<div class="container">
			<div class="header-top">
				<div class="logo">
					<h1>
						<a href="index.html">乐途旅游</a>
					</h1>
				</div>
				<!-- place holder for switch language. no css style now.
						<div class="switch-language"></div>
						 -->
				<div class="clearfix"></div>
			</div>
			<div class="header-bottom">
				<nav class="navbar navbar-default">
					<div class="container-fluid">
						<!-- Brand and toggle get grouped for better mobile display -->
						<div class="navbar-header">
							<button type="button" class="navbar-toggle collapsed"
								data-toggle="collapse"
								data-target="#bs-example-navbar-collapse-1"
								aria-expanded="false">
								<span class="sr-only">Toggle navigation</span> <span
									class="icon-bar"></span> <span class="icon-bar"></span> <span
									class="icon-bar"></span>
							</button>
						</div>
						<!-- Collect the nav links, forms, and other content for toggling -->
						<div class="collapse navbar-collapse"
							id="bs-example-navbar-collapse-1">
							<ul id="main-navbar" class="nav navbar-nav cl-effect-16">
								<li id="text-manage-tab-header"><a class="text-manage-url" href="">文字管理<span
										class="sr-only"></span></a></li>
								<li id="ct-manage-tab-header" class="dropdown"><a href=""
									class="customized-travel-manage-dropdown-toggle dropdown-toggle" role="button"
									aria-haspopup="true" aria-expanded="false">订制旅游管理<span
										class="caret"></span></a>
									<ul class="customized-travel-manage-dropdown dropdown-menu">
										<li><a href='/administration/customizedtravel/addarea'>添加景点</a></li>		
										<li><a href='/administration/customizedtravel/editarea'>编辑景点</a></li>	
										<li style="padding-left:5em; cursor:default;" onclick="foldAreaList();">[收起]</li>							
									</ul>
								</li>
								<li id="shuttle-manage-tab-header" class="dropdown"><a href=""
								class="shuttle-service-manage-dropdown-toggle dropdown-toggle" role="button"
									aria-haspopup="true" aria-expanded="false">专车服务管理<span
										class="caret"></span></a>
									<ul class="shuttle-service-manage-dropdown dropdown-menu">
										<li><a href='/administration/shuttleservice/manageitinerary'>管理行程</a></li>		
										<li><a href='/administration/shuttleservice/additinerary'>添加目的地</a></li>	
										<li style="padding-left:5em; cursor:default;" onclick="foldAreaList();">[收起]</li>							
									</ul>
								</li>
							</ul>
						</div>
						<!-- /.navbar-collapse -->
					</div>
					<!-- /.container-fluid -->
				</nav>
			</div>
		</div>
	</div>
	<!--end header-section-->
		
    	<?php echo $this->content; ?> 
    	          		
		<!--footer-->
	<div class="footer-section">
		<div class="container">
			<div class="footer-top">
				<p>联系我们：电话 +16666666666 &nbsp&nbsp 邮箱 happyjourney@gmail.com</p>
			</div>

		</div>
	</div>
	<!--footer-->
</body>
</html>