<div class="content">
	<div class="contact">
		<div class="container">
			<div id="list-ss-message-div">
				<?php if($this->result != null):?>
					<?php foreach($this->result['itineraries'] as $item):?>
						<div id="itinerary-div-<?php echo $item->Id;?>">
							<table class="list-contact-table">
								<tr><th>名</th><th>姓</th><th>时间</th><th>电话</th><th>邮件</th><th>微信</tr>
								<tr>
									<td><?php echo $item->FirstName;?></td>
									<td><?php echo $item->LastName;?></td>
									<td><?php echo $item->CreationTime;?></td>
									<td><?php echo $item->Phone;?></td>
									<td><?php echo $item->Email;?></td>
									<td><?php echo $item->Wechat;?></td>
								</tr>
							</table>
							<div class="display-message-div">
								<span>留言： </span>
								<span class="display-message"><?php echo $item->Message;?></span>
							</div>
							<?php if($item->CustomerItineraryId != null):?>
								<div class="display-message-div"><span>所选行程：</span></div>
								<table class="list-itinerary-table">
									<tr><th>目的地</th><th>时间</th><th>车辆</th></tr>
									<tr>
										<td><?php echo $item->Destination;?></td>
										<td><?php echo $item->Date." ".$item->Hour.": ".$item->Minute;?></td>
										<td><?php echo $item->Vehicle;?></td>
									</tr>
								</table>
							<?php endif;?>
							<div class="itinerary-status-div">
								<?php if($item->Deleted):?>
									<div class="display-message-div"><span class="information-message">此条留言已被受理</span></div>
								<?php else:?>
									<div class="delete-message-div"><button class="delete-itinerary-btn" data-Id=<?php echo $item->Id;?> data-customeritineraryid=<?php echo $item->CustomerItineraryId;?>>标记为已受理</button></div>
								<?php endif;?>
							</div>
							<br>
							<br>
						</div>
					<?php endforeach;?>					
					<div class="ss-itinerary-pages-div">
						<?php if($this->result['current'] != 1):?>
						<span><a href="/administration/shuttleservice/1">首页</a></span>
						<?php endif;?>						
						<?php if($this->result['previous'] != null):?>
						<span><a href="/administration/shuttleservice/<?php echo $this->result['previous'];?>">前一页</a></span>
						<?php endif;?>						
						<span><?php echo $this->result['current'];?></span>						
						<?php if($this->result['next'] != null):?>
						<span><a href="/administration/shuttleservice/<?php echo $this->result['next'];?>">后一页</a></span>
						<?php endif;?>						
						<?php if($this->result['last'] != $this->result['current']):?>
						<span><a href="/administration/shuttleservice/<?php echo $this->result['last'];?>"><?php echo $this->result['last'];?></a></span>
						<?php endif;?>						
					</div>
				<?php else:?>
					没有更多留言。
				<?php endif;?>
		 	 </div>
		</div>
	</div>
</div>