<div class="content">
	<div class="contact">
		<div class="container">
			<div class="add-area-div">
				<div class="area-detail-div">
					<div>
						<div>景点名称： </div>
						<input type="text" />
					</div>
					<div class="area-area-textarea-div">
						<div>描述：</div>
						<textarea rows="10" col="40"></textarea>
					</div>
				</div>
				<div class="add-area-submit-div">
					<button>添加</button>
				</div>
				<span class="error-message"></span> 
				<br>
			</div>
		</div>
	</div>
</div>