<div class="content">
	<div class="contact">
		<div class="container">
			<div id="list-area-div">
				<?php if($this->result != null):?>
					<?php foreach($this->result as $item):?>
						<div id="area-div-<?php echo $item['Id'];?>" class="display-area-div">
							<div class="area-detail-div">
								<div>景点：<?php echo $item['Name'];?></div>
								<div class="area-edit-div">
									<div>介绍： </div>
									<textarea rows="10" col="40"><?php echo $item['Description'];?></textarea>
								</div>
							</div>
							<div class="edit-area-submit-div" data-Id=<?php echo $item['Id'];?>>
								<button data-type="edit">提交编辑</button>
								<button data-type="delete">删除</button>
							</div>
							<span class="error-message"></span>
							<br>
						</div>
					<?php endforeach;?>					
				<?php else:?>
					没有更多条目。
				<?php endif;?>
		 	 </div>
		</div>
	</div>
</div>