<div class="content">
	<div class="contact">
		<div class="container">
			<div class="contact-grids">
				<div class="col-md-6 contact-right">
				  <div class="image area-detail-img">
				  	<img class="img-responsive" src="/images/area/area-detail-<?php echo $this->result['Id'];?>.jpg">
				  </div>
				</div>
				<div class="col-md-6 contact-left">
					<h3><?php echo $this->result['Name'];?></h3>
					<br>
					<p><?php echo $this->result['Description'];?></p>
				</div>
				<div class="clearfix"></div>
			</div>
		</div>
	</div>		
</div>