<div class="content">
	<div class="contact">
		<div class="container">
			<div class="contact-grids">
				<div class="col-md-6 contact-right">
					<div id="ss-destination-div" class="rounded-border ss-selection-div">
					 	<div class="ss-selection-header">选择目的地</div>
						 <div class="ss-selection-content" style="display: none;">
					 		<?php if($this->results->destinations != null):?>
					 		<ul class="selection-ul">
					 		<?php foreach($this->results->destinations as $destination):?>
					 		<li class="unselected-li" data-destinationid="<?php echo $destination['Id'];?>"><?php echo $destination['Name'];?></li>
					 		<?php endforeach;?>
					 		</ul>
					 		<?php endif;?>
					 		<button class="ss-selection-btn">确认</button>
					 	</div>
					</div>
					<div id="ss-destination-error" class="error-message">* 请选择目的地</div>
					<br>
					<div id="ss-date-div" class="rounded-border ss-selection-div" style="display: none;">
					 	<div class="ss-selection-header">选择日期</div>
					 	<div class="ss-selection-content">
					 	<p>Date: <input type="text" class="datepicker"></p>
					 	<button class="ss-selection-btn">确认</button>
					 	</div>
					</div>
					<div id="ss-date-error" class="error-message">* 请选择日期</div>
					<br>
					<div id="ss-time-div" class="rounded-border ss-selection-div" style="display: none;">
					 	<div class="ss-selection-header">选择时间</div>
					 	<div class="ss-selection-content">
						 	<select id="ss-hour-select">
						 	  <option value="" disabled selected>----</option>
							  <?php for($i=0; $i<24; $i++):?>
							  <option value="<?php echo $i;?>"><?php echo $i;?></option>
							  <?php endfor;?>
							</select>
							点&nbsp
							<select id="ss-minute-select">
							  <option value="" disabled selected>----</option>
							  <?php for($i=0; $i<59; $i++):?>
							  <option value="<?php echo $i;?>"><?php echo $i<10?("0".$i):$i;?></option>
							  <?php endfor;?>
							</select>
							分
							<br>
						 	<button class="ss-selection-btn">确认</button>
					 	</div>
					</div>
					<div id="ss-time-error" class="error-message">* 请选择时间</div>
					<br>
					<div id="ss-itinerary-div" class="rounded-border ss-selection-div" style="display: none;">
					 	<div class="ss-selection-header">选择车次</div>
					 	<div class="ss-selection-content">
					 	San Diego<br>
					 	Los Angeles<br>
					 	</div>
					</div>
					<div id="ss-itinerary-error" class="error-message">* 请选择车次</div>
					<br>
					<button id="ss-submit" class="ss-selection-btn" style="display:none;">确认提交</button>
				</div>
				<div class="col-md-6 contact-left">
					<p><?php echo $this->results->text;?></p>
				</div>
				<div class="clearfix"></div>
			</div>
		</div>
	</div>		
</div>