<?php echo $this->doctype(); ?>

<html lang="zh">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle($this->translate('Happy Journey'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0') ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/images/favicon.ico'))
                        ->prependStylesheet($this->basePath() . '/css/bootstrap.css')
                        ->prependStylesheet($this->basePath() . '/css/style.css') 
        				->prependStylesheet($this->basePath() . '/css/flexslider.css')?>
        <link href='//fonts.googleapis.com/css?family=Open+Sans:400,800italic,800,700italic,700,600italic,600,400italic,300italic,300' rel='stylesheet' type='text/css'>

        <!-- Scripts -->
        <?php echo $this->headScript()->prependFile($this->basePath() . '/js/responsiveslides.min.js')
                                      ->prependFile($this->basePath() . '/js/jquery-1.11.1.min.js')
                                      ->prependFile($this->basePath() . '/js/bootstrap.js') ?>
		<script type="application/x-javascript"> addEventListener("load", function() { setTimeout(hideURLbar, 0); }, false); function hideURLbar(){ window.scrollTo(0,1); } </script>
		<script>
		    $(function () {
		      $("#slider").responsiveSlides({
		      	auto: true,
		      	nav: true,
		      	speed: 500,
		        namespace: "callbacks",
		        pager: true,
		      });
		    });		
	  </script>        
    </head>
    <body>
	    <div class="header">
			<div class="container">
					<div class="header-top">
						<div class="logo">
							<h1><a href="index.html">乐途旅游</a></h1>
						</div>
						<!-- place holder for switch language. no css style now.
						<div class="switch-language"></div>
						 -->
						<div class="clearfix"></div>
					</div>
				<div class="header-bottom">
					<nav class="navbar navbar-default">
						<div class="container-fluid">
						<!-- Brand and toggle get grouped for better mobile display -->
						<div class="navbar-header">
							<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
								<span class="sr-only">Toggle navigation</span>
								<span class="icon-bar"></span>
								<span class="icon-bar"></span>
								<span class="icon-bar"></span>
							</button>
						</div>
	        			<!-- Collect the nav links, forms, and other content for toggling -->
							<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
							  <ul class="nav navbar-nav cl-effect-16">
								<li class="active"><a href="index.html">Home <span class="sr-only">(current)</span></a></li>
								<li><a href="about.html">About</a></li>
								 <li class="dropdown">
								  <a href="services.html" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Services<span class="caret"></span></a>
								  <ul class="dropdown-menu">
									 <li><a href="services.html">Services1</a></li>
									<li><a href="services.html">Services2</a></li>
									<li><a href="services.html">Services3</a></li>
								  </ul>
								</li>
									<li><a href="gallery.html">Gallery</a></li>
									<li><a href="codes.html">Codes</a></li>
									<li><a href="contact.html">Contact</a></li>
								</ul>
							</div><!-- /.navbar-collapse -->
						</div><!-- /.container-fluid -->
					</nav>
				</div>
			</div>
		</div>
		<!--end header-section-->
		
    	<?php echo $this->content; ?> 
    	          		
		<!--footer-->
		<div class="footer-section">
			<div class="container">
				<div class="footer-top">
					<p>
						Copyright &copy; 2015 Super Bikes. All Rights Reserved | Design by<a
							href="http://w3layouts.com" target="target_blank">W3layouts</a>
					</p>
				</div>
		
			</div>
		</div>
		<!--footer-->
    </body>
</html>
