<div class="login-body">
	<div id="loginDiv" class="horizontal-center">
		<div class="login-form-item">
			<input type="text" id="login-username" /> 用户名<br>
			<span class="error-message">请输入正确的用户名</span>
		</div>
		<div class="login-form-item">
			<input type="PASSWORD" id="login-password" /> 密码<br>
			<span class="error-message">请输入正确的密码</span>
		</div>
		<div style="text-align: center;">
			<div class="login-form-item"><input type="checkbox" id="login-rememberme" value="rememberme"/> 保持登陆</div>
			<div class="login-form-item"><input type="submit" id="loginSubmit" value="提交" style="width: 5em;"/> </div>
		</div>
		<div class="error-message">错误</div>
	</div>
</div>
