
<!--banner-->
<section class="slider2">
	<div class="flexslider">
		<ul class="slides">
			<li>
				<div class="slider-info">
					<img src="images/ban.jpg" class="img-responsive" alt="">
				</div>
			</li>
			<li>
				<div class="slider-info">
					<img src="images/ban1.jpg" class="img-responsive" alt="">
				</div>
			</li>
			<li>
				<div class="slider-info">
					<img src="images/ban2.jpg" class="img-responsive" alt="">
				</div>
			</li>

		</ul>
	</div>
</section>
<!--FlexSlider-->
<script defer src="js/jquery.flexslider.js"></script>
<script type="text/javascript">
	$(function(){
	  SyntaxHighlighter.all();
	});
	$(window).load(function(){
	  $('.flexslider').flexslider({
		animation: "slide",
		start: function(slider){
		  $('body').removeClass('loading');
		}
	  });
	});
</script>
<!--FlexSlider-->
<!-- slider -->

<!--banner-->
<!--welcome-->
<div class="content">
	<div class="welcome">
		<div class="container">
			<div class="welcome-grids">
				<div class="col-md-6 welcome-grid">
					<img src="images/p1.jpg" class="img-responsive" alt="">
				</div>
				<div class="col-md-6 welcome-grid1">
					<h2>Welcome to our page</h2>
					<h4>Vestibulum interdum mi sit amet</h4>
					<p>Lorem ipsum dolor sit t, consectetuer adipiscing elit.
						Praesentstibulum molestie lacus. Aenean nonumy hendrerit mauris.
						Phasellus porta. Fusce cipit varius mi. Cum sociis natoque
						penatibus et dis parturient montes, nasus. Nulla dui. Fusce
						feugiat malesuada odio.</p>
				</div>
				<div class="clearfix"></div>
			</div>
		</div>
	</div>
	<!--welcome-->
</div>
<?php print_r($this->results);?>