
<!--banner-->
<section class="slider2">
	<div class="flexslider">
		<ul class="slides">
			<li>
				<div class="slider-info">
					<img src="images/ban1.jpg" class="img-responsive" alt="">
				</div>
			</li>
			<li>
				<div class="slider-info">
					<img src="images/ban2.jpg" class="img-responsive" alt="">
				</div>
			</li>
			<li>
				<div class="slider-info">
					<img src="images/ban3.jpg" class="img-responsive" alt="">
				</div>
			</li>

		</ul>
	</div>
</section>
<!--FlexSlider-->
<script type="text/javascript">
	$(window).load(function(){
	  $('.flexslider').flexslider({
		animation: "slide",
		start: function(slider){
		  $('body').removeClass('loading');
		}
	  });
	});
</script>
<!--FlexSlider-->
<!-- slider -->

<!--banner-->
<!--welcome-->
<div class="content">
	<div class="welcome">
		<div class="container">
			<div class="welcome-grids">
				<div class="col-md-6 welcome-grid">
					<img src="images/p1.jpg" class="img-responsive" alt="">
				</div>
				<div class="col-md-6 welcome-grid1">
					<h2>欢迎访问乐途旅游！</h2>
					<h4>Enjoy your trip in America's finest city!</h4>
				</div>
				<div class="clearfix"></div>
			</div>
		</div>
	</div>
	<!--welcome-->
</div>