<div id="text-manage-div" class="admin-page-modal">
	<div id="edit-ct-text" class="rounded-border text-manage-section">
		 <div class="text-manage-section-header">编辑定制旅游主页文字</div>
		 <div class="text-manage-section-content" style="display: block;">
	 		<span id="ct-text-manage-textarea"><textarea style="width: 95%; height: 10em;"></textarea></span>
	 		<button class="text-manage-submit">提交</button>
	 	</div>
	</div>
	<br>
	<div id="edit-ss-text" class="rounded-border text-manage-section">
		 <div class="text-manage-section-header">编辑专车服务主页文字</div>
		 <div class="text-manage-section-content" style="display: block;">
	 		<span id="ss-text-manage-textarea"><textarea style="width: 95%; height: 10em;"></textarea></span>
	 		<button class="text-manage-submit">提交</button>
	 	</div>
	</div>
</div>